//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalcazzAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conceptos
    {
        public long IdConcepto { get; set; }
        public string Concepto { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public long IdFactura { get; set; }
    
        public virtual Facturas Facturas { get; set; }
    }
}
